name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup kubectl
      run: |
        mkdir -p ~/.kube
        echo "apiVersion: v1
kind: Config
clusters:
- cluster:
    server: ${{ secrets.K8S_SERVER }}
    insecure-skip-tls-verify: true
  name: cluster
contexts:
- context:
    cluster: cluster
    user: user
  name: context
current-context: context
users:
- name: user
  user:
    token: ${{ secrets.K8S_TOKEN }}" > ~/.kube/config
    
    - name: Deploy to Kubernetes
      run: |
        sed -i "s|image: .*/wisecow:.*|image: ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.event.workflow_run.run_number }}|" wisecow-deployment.yaml
        kubectl apply -f wisecow-deployment.yaml
        kubectl apply -f wisecow-service.yaml
        kubectl apply -f wisecow-ingress-selfsigned.yaml